// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using Azure.Core;

namespace ScaleArch.ApiTemplate.Client
{
    /// <summary> Client options for ApiClient. </summary>
    public partial class ApiClientOptions : ClientOptions
    {
        private const ServiceVersion LatestVersion = ServiceVersion.V1;

        /// <summary> The version of the service to use. </summary>
        public enum ServiceVersion
        {
            /// <summary> Service version "v1". </summary>
            V1 = 1,
        }

        internal string Version { get; }

        /// <summary> Initializes new instance of ApiClientOptions. </summary>
        public ApiClientOptions(ServiceVersion version = LatestVersion)
        {
            Version = version switch
            {
                ServiceVersion.V1 => "v1",
                _ => throw new NotSupportedException()
            };
        }
    }
}
